export interface MESSAGE_TYPE {
  id: string;
  subject: string;
  name: string;
  email: string;
  createdAt: string;
  message: string;
}

export enum PROJECT_KEYWORD {
  TAILWINDCSS = "Tailwind CSS",
  MATERIALUI = "Material UI",
  FIGMA = "Figma",
  BOOTSTRAP = "Bootstrap",
  MONGODB = "MongoDB",
  NEXTJS = "Next.js",
  PRISMA = "Prisma",
  GRAPHQL = "GraphQL",
  TYPESCRIPT = "TypeScript",
  VITE = "Vite",
  EXPRESSJS = "Express.js",
  FIREBASE = "Firebase",
  PYTHON = "Python",
  REDUX = "Redux",
  GIT = "Git",
  DOCKER = "Docker",
  MYSQL = "MySQL",
  SEQUELIZE = "Sequelize",
  GITHUB = "GitHub",
  NUMPY = "Numpy",
  PANDAS = "Pandas",
  NODE = "Node",
  REACT = "React",
  JAVASCRIPT = "JavaScript",
  HTML = "HTML",
  CSS = "CSS",
  FRAMER_MOTION = "Framer Motion",
  CHAKRA_UI = "Chakra UI",
  FLOWBITE = "Flowbite",
  SHADCN_UI = "Shadcn UI",
  REDUX_TOOLKIT = "Redux Toolkit",
  REACT_QUERY = "React Query",
  REDUX_TOOLKIT_QUERY = "Redux Toolkit Query",
  JEST = "Jest",
  CYPRESS = "Cypress",
  AUTHJS = "Auth.js",
  PRIMER_REACT = "Primer React",
  DAISY_UI = "Daisy UI",
  REDUCER = "Reducer",
  REACT_CONTEXT = "React Context",
  REACT_ROUTER = "React Router",
  REACT_HOOKS = "React Hooks",
  GITHUB_PAGES = "GitHub Pages",
  REST_API = "REST API",
  GRAPHQL_API = "GraphQL API",
  EXPRESS_VALIDATOR = "Express Validator",
  WINSTON_LOGGER = "Winston Logger",
  CLOUDINARY = "Cloudinary",
  APOLLO_CLIENT = "Apollo Client",
  APOLLO_SERVER = "Apollo Server",
}
